FROM java:8

MAINTAINER <Author>

RUN java -version



#RUN apt-get update  
#RUN apt-get install -y maven

#COPY . /usr/src/myapp

#WORKDIR /usr/src/myapp

#ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

#ADD pom.xml /code/pom.xml  
#RUN ["mvn", "dependency:resolve"]  
#RUN ["mvn", "verify"]

#ADD src /code/src  
#RUN ["mvn", "package"]
#RUN javac Main.java

#CMD ["java", "Main"]

#EXPOSE 4567  
#CMD ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "target/jar-with-dependencies.jar"]  

